import { applyEvent, replay } from "./world-core";
import type { WorldEvent, WorldState } from "./world-core";

/** Minimal D1 surface: no Cloudflare runtime required to typecheck this module. */
export interface D1Statement {
  bind(...values: unknown[]): D1Statement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<{ results: T[] }>;
}
export interface D1Database {
  prepare(sql: string): D1Statement;
  batch(statements: D1Statement[]): Promise<unknown[]>;
}
type SessionRow = { initial_json: string };
type EventRow = { event_json: string };
export type PersistedSession = { initial: WorldState; events: WorldEvent[]; state: WorldState };

function parseJSON<T>(value: string): T { return JSON.parse(value) as T; }

/** Create a new immutable starting snapshot. IDs are server-generated by the caller. */
export async function createSession(db: D1Database, sessionId: string, initial: WorldState): Promise<void> {
  if (!sessionId.trim() || initial.cycle !== 0) throw new Error("Invalid initial session");
  await db.batch([db.prepare("INSERT INTO sherlock_sessions (id, initial_json) VALUES (?, ?)")
    .bind(sessionId, JSON.stringify(initial))]);
}

/** Read all events in append order, then reconstruct state from the original snapshot. */
export async function loadSession(db: D1Database, sessionId: string): Promise<PersistedSession | null> {
  const row = await db.prepare("SELECT initial_json FROM sherlock_sessions WHERE id = ?")
    .bind(sessionId).first<SessionRow>();
  if (!row) return null;
  const eventRows = await db.prepare(
    "SELECT event_json FROM sherlock_events WHERE session_id = ? ORDER BY sequence ASC"
  ).bind(sessionId).all<EventRow>();
  const initial = parseJSON<WorldState>(row.initial_json);
  const events = eventRows.results.map(row => parseJSON<WorldEvent>(row.event_json));
  return { initial, events, state: replay(initial, events) };
}

/** Append exactly one complete validated cycle, atomically.
 * The unique (session_id, cycle) cycle-start row prevents two writers from
 * committing the same cycle. D1 batch is transactional: failure rolls back all.
 */
export async function appendCycle(
  db: D1Database, sessionId: string, expectedCycle: number, events: readonly WorldEvent[]
): Promise<WorldState> {
  if (!Number.isSafeInteger(expectedCycle) || expectedCycle < 0) throw new Error("Invalid expected cycle");
  if (!events.length || events[0].type !== "cycle.started" || events[0].cycle !== expectedCycle + 1)
    throw new Error("A cycle must start with its next cycle.started event");
  const session = await loadSession(db, sessionId);
  if (!session) throw new Error("Session not found");
  if (session.state.cycle !== expectedCycle) throw new Error("Stale cycle");
  let next = session.state;
  for (let i = 0; i < events.length; i++) {
    const event = events[i];
    if (event.id !== `${expectedCycle + 1}:${i}` || event.cycle !== expectedCycle + 1 ||
        (i > 0 && event.type === "cycle.started")) throw new Error("Malformed cycle event");
    next = applyEvent(next, event);
  }
  const statements = events.map((event, i) => db.prepare(
    "INSERT INTO sherlock_events (session_id, cycle, position, event_id, event_json) VALUES (?, ?, ?, ?, ?)"
  ).bind(sessionId, event.cycle, i, event.id, JSON.stringify(event)));
  await db.batch(statements);
  return next;
}
