import type { ZoneKey } from "./data";

/** Authored narrative fragments, not messages generated by a live character or Octopus. */
export const characterInterventions: Record<ZoneKey, readonly { name: string; text: string }[]> = {
  port: [{ name: "MARIE JEANNE", text: "Bienvenue au port de Porsa Rotas. C'est ici que commence la traversée." }],
  max: [{ name: "MAX LIBERTY", text: "Au comptoir, les histoires arrivent toujours avant les voyageurs." }],
  sator: [{ name: "MARTY", text: "SATOR. Tu peux le lire dans tous les sens ; ça ne te dira pas ce qui vient ensuite." }],
  ludmila: [{ name: "LUDMILA", text: "Ici, même les souvenirs dansent à contretemps." }],
  institute: [{ name: "NIKOLAS", text: "Ne touche pas aux prototypes sans regarder ce qu'ils ont déjà inventé." }],
  network: [{ name: "NATASHA", text: "Le signal passe. Pour le reste, on verra après le direct." }],
};
